import { useState } from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import { ExternalLink, Github, Pencil, Plus, Search, Star, Trash2 } from "lucide-react";
import type { PortfolioProject } from "@shared/schema";
import { AdminShell } from "@/components/admin/AdminShell";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { apiRequest, queryClient } from "@/lib/queryClient";

const emptyProject = { title: "", slug: "", description: "", category: "Software", techStack: "", challenge: "", solution: "", outcome: "", featuredImage: "", liveUrl: "", githubUrl: "", featured: false, order: 0 };

export default function PortfolioManagement() {
  const [search, setSearch] = useState("");
  const [editingId, setEditingId] = useState<string | null>(null);
  const [editorOpen, setEditorOpen] = useState(false);
  const [form, setForm] = useState(emptyProject);
  const projects = useQuery<PortfolioProject[]>({ queryKey: ["/api/portfolio"] });
  const reset = () => { setEditingId(null); setEditorOpen(false); setForm(emptyProject); };
  const save = useMutation({ mutationFn: () => apiRequest(editingId ? "PUT" : "POST", editingId ? `/api/portfolio/${editingId}` : "/api/portfolio", { ...form, techStack: form.techStack.split(",").map(item => item.trim()).filter(Boolean), featuredImage: form.featuredImage || null, liveUrl: form.liveUrl || null, githubUrl: form.githubUrl || null, challenge: form.challenge || null, solution: form.solution || null, outcome: form.outcome || null }), onSuccess: () => { queryClient.invalidateQueries({ queryKey: ["/api/portfolio"] }); queryClient.invalidateQueries({ queryKey: ["/api/admin/overview"] }); reset(); } });
  const remove = useMutation({ mutationFn: (id: string) => apiRequest("DELETE", `/api/portfolio/${id}`), onSuccess: () => { queryClient.invalidateQueries({ queryKey: ["/api/portfolio"] }); queryClient.invalidateQueries({ queryKey: ["/api/admin/overview"] }); } });
  const edit = (project: PortfolioProject) => { setEditingId(project.id); setEditorOpen(true); setForm({ title: project.title, slug: project.slug, description: project.description, category: project.category, techStack: project.techStack?.join(", ") ?? "", challenge: project.challenge ?? "", solution: project.solution ?? "", outcome: project.outcome ?? "", featuredImage: project.featuredImage ?? "", liveUrl: project.liveUrl ?? "", githubUrl: project.githubUrl ?? "", featured: project.featured ?? false, order: project.order ?? 0 }); window.scrollTo({ top: 0, behavior: "smooth" }); };
  const visible = projects.data?.filter(project => `${project.title} ${project.description} ${project.category}`.toLowerCase().includes(search.toLowerCase())) ?? [];
  return <AdminShell title="Portfolio" description="Manage case studies, project evidence, links, and featured work"><div className="space-y-6">
    <div className="flex gap-3"><div className="relative flex-1"><Search className="absolute left-3 top-3 h-4 w-4 text-white/25"/><Input className="pl-9" value={search} onChange={event => setSearch(event.target.value)} placeholder="Search projects"/></div><Button onClick={() => { reset(); setEditorOpen(true); }}><Plus className="mr-2 h-4 w-4"/>New project</Button></div>
    {editorOpen && <Card className="border-primary/20 bg-primary/[0.03]"><CardHeader><CardTitle className="text-base">{editingId ? "Edit project" : "Create project"}</CardTitle></CardHeader><CardContent className="space-y-4"><div className="grid gap-4 md:grid-cols-2"><Input placeholder="Project title" value={form.title} onChange={event => setForm({ ...form, title: event.target.value })}/><Input placeholder="URL slug" value={form.slug} onChange={event => setForm({ ...form, slug: event.target.value.toLowerCase().replace(/[^a-z0-9-]+/g, "-") })}/><Input placeholder="Category" value={form.category} onChange={event => setForm({ ...form, category: event.target.value })}/><Input placeholder="Technology stack, comma separated" value={form.techStack} onChange={event => setForm({ ...form, techStack: event.target.value })}/><Input placeholder="Live URL" value={form.liveUrl} onChange={event => setForm({ ...form, liveUrl: event.target.value })}/><Input placeholder="GitHub URL" value={form.githubUrl} onChange={event => setForm({ ...form, githubUrl: event.target.value })}/></div><Input placeholder="Featured image URL" value={form.featuredImage} onChange={event => setForm({ ...form, featuredImage: event.target.value })}/><Textarea placeholder="Project description" value={form.description} onChange={event => setForm({ ...form, description: event.target.value })}/><div className="grid gap-4 lg:grid-cols-3"><Textarea placeholder="Challenge" value={form.challenge} onChange={event => setForm({ ...form, challenge: event.target.value })}/><Textarea placeholder="Solution" value={form.solution} onChange={event => setForm({ ...form, solution: event.target.value })}/><Textarea placeholder="Outcome" value={form.outcome} onChange={event => setForm({ ...form, outcome: event.target.value })}/></div><label className="flex items-center gap-2 text-sm text-white/60"><input type="checkbox" checked={form.featured} onChange={event => setForm({ ...form, featured: event.target.checked })}/>Feature this project</label><div className="flex gap-2"><Button disabled={!form.title || !form.slug || !form.description || save.isPending} onClick={() => save.mutate()}>{save.isPending ? "Saving…" : "Save project"}</Button><Button variant="outline" onClick={reset}>Cancel</Button></div></CardContent></Card>}
    <div className="grid gap-4 lg:grid-cols-2">{visible.map(project => <Card key={project.id} className="overflow-hidden border-white/[0.07] bg-white/[0.025]"><CardContent className="p-5"><div className="flex items-start gap-4">{project.featuredImage ? <img src={project.featuredImage} alt="" className="h-20 w-24 rounded-lg object-cover"/> : <div className="flex h-20 w-24 items-center justify-center rounded-lg bg-white/[0.04]"><Star className="h-5 w-5 text-white/15"/></div>}<div className="min-w-0 flex-1"><div className="flex items-center gap-2"><h2 className="truncate font-semibold">{project.title}</h2>{project.featured && <Star className="h-3.5 w-3.5 fill-amber-400 text-amber-400"/>}</div><Badge variant="outline" className="mt-2">{project.category}</Badge><p className="mt-3 line-clamp-2 text-sm text-white/40">{project.description}</p></div></div><div className="mt-4 flex flex-wrap items-center gap-2 border-t border-white/[0.06] pt-4">{project.liveUrl && <Button size="sm" variant="ghost" asChild><a href={project.liveUrl} target="_blank" rel="noreferrer"><ExternalLink className="mr-2 h-4 w-4"/>Live</a></Button>}{project.githubUrl && <Button size="sm" variant="ghost" asChild><a href={project.githubUrl} target="_blank" rel="noreferrer"><Github className="mr-2 h-4 w-4"/>Code</a></Button>}<div className="flex-1"/><Button size="sm" variant="outline" onClick={() => edit(project)}><Pencil className="mr-2 h-4 w-4"/>Edit</Button><Button size="icon" variant="ghost" className="text-destructive" onClick={() => { if (window.confirm(`Delete “${project.title}”?`)) remove.mutate(project.id); }}><Trash2 className="h-4 w-4"/></Button></div></CardContent></Card>)}{!projects.isLoading && !visible.length && <div className="col-span-full rounded-xl border border-dashed border-white/10 py-16 text-center text-sm text-white/35">No projects match this view.</div>}</div>
  </div></AdminShell>;
}
