import { useState } from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import { Clock3, KeyRound, Laptop, Search, ShieldAlert, ShieldCheck } from "lucide-react";
import { AdminShell } from "@/components/admin/AdminShell";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { apiRequest, queryClient } from "@/lib/queryClient";

interface SecurityEvent { id: string; type: string; severity: string; userId: string | null; metadata: unknown; createdAt: string }
interface SessionRecord { id: string; userId: string; email: string | null; userAgent: string | null; createdAt: string; lastSeenAt: string; expiresAt: string; revokedAt: string | null; revokedReason: string | null }
interface AuditRecord { id: string; action: string; resourceType: string; resourceId: string | null; result: string; justification: string | null; actorUserId: string | null; createdAt: string }

export default function SecurityManagement() {
  const [view, setView] = useState<"sessions" | "events" | "audit">("sessions");
  const [search, setSearch] = useState("");
  const sessions = useQuery<SessionRecord[]>({ queryKey: ["/api/admin/security/sessions"] });
  const events = useQuery<SecurityEvent[]>({ queryKey: ["/api/admin/security/events"] });
  const audit = useQuery<AuditRecord[]>({ queryKey: [`/api/admin/audit?search=${encodeURIComponent(search)}`] });
  const revoke = useMutation({ mutationFn: ({ id, justification }: { id: string; justification: string }) => apiRequest("POST", `/api/admin/security/sessions/${id}/revoke`, { justification }), onSuccess: () => { queryClient.invalidateQueries({ queryKey: ["/api/admin/security/sessions"] }); queryClient.invalidateQueries({ queryKey: ["/api/admin/audit?search="] }); } });
  const active = sessions.data?.filter(session => !session.revokedAt && new Date(session.expiresAt) > new Date()).length ?? 0;
  const severe = events.data?.filter(event => ["high", "critical"].includes(event.severity)).length ?? 0;
  return <AdminShell title="Security and accountability" description="Sessions, security events, and immutable administrative audit history"><div className="space-y-6">
    <section className="grid gap-3 sm:grid-cols-3"><Card className="border-white/[0.07] bg-white/[0.025]"><CardContent className="flex items-center gap-4 p-5"><Laptop className="h-6 w-6 text-primary"/><div><p className="text-2xl font-black">{active}</p><p className="text-xs text-white/35">Active sessions</p></div></CardContent></Card><Card className="border-white/[0.07] bg-white/[0.025]"><CardContent className="flex items-center gap-4 p-5"><ShieldAlert className="h-6 w-6 text-amber-400"/><div><p className="text-2xl font-black">{severe}</p><p className="text-xs text-white/35">High-severity events</p></div></CardContent></Card><Card className="border-white/[0.07] bg-white/[0.025]"><CardContent className="flex items-center gap-4 p-5"><KeyRound className="h-6 w-6 text-emerald-400"/><div><p className="text-2xl font-black">{audit.data?.length ?? 0}</p><p className="text-xs text-white/35">Recent audit records</p></div></CardContent></Card></section>
    <div className="flex flex-wrap gap-2">{(["sessions","events","audit"] as const).map(item => <Button key={item} variant={view === item ? "default" : "outline"} onClick={() => setView(item)} className="capitalize">{item}</Button>)}</div>
    {view === "audit" && <div className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-white/25"/><Input className="pl-9" value={search} onChange={event => setSearch(event.target.value)} placeholder="Search action, resource, or result"/></div>}
    {view === "sessions" && <div className="space-y-3">{sessions.data?.map(session => { const sessionActive = !session.revokedAt && new Date(session.expiresAt) > new Date(); return <Card key={session.id} className="border-white/[0.07] bg-white/[0.025]"><CardContent className="flex flex-col gap-4 p-5 md:flex-row md:items-center"><div className={`flex h-10 w-10 items-center justify-center rounded-xl ${sessionActive ? "bg-emerald-500/10 text-emerald-400" : "bg-white/[0.04] text-white/25"}`}><Laptop className="h-5 w-5"/></div><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><p className="truncate text-sm font-medium">{session.email}</p><Badge variant="outline" className={sessionActive ? "border-emerald-500/30 text-emerald-400" : "text-white/30"}>{sessionActive ? "Active" : session.revokedAt ? "Revoked" : "Expired"}</Badge></div><p className="mt-1 truncate text-xs text-white/30">{session.userAgent || "Unknown device"}</p><p className="mt-1 text-[10px] text-white/20">Last seen {new Date(session.lastSeenAt).toLocaleString()}</p>{session.revokedReason && <p className="mt-2 text-xs text-amber-300/70">Reason: {session.revokedReason}</p>}</div>{sessionActive && <Button variant="destructive" size="sm" disabled={revoke.isPending} onClick={() => { const justification = window.prompt("Provide a justification for revoking this session (minimum 8 characters):"); if (justification && justification.trim().length >= 8) revoke.mutate({ id: session.id, justification: justification.trim() }); }}>Revoke</Button>}</CardContent></Card>; })}</div>}
    {view === "events" && <div className="space-y-3">{events.data?.map(event => <div key={event.id} className="flex items-start gap-3 rounded-xl border border-white/[0.07] bg-white/[0.025] p-4"><ShieldAlert className={`mt-0.5 h-4 w-4 ${event.severity === "critical" ? "text-red-400" : event.severity === "high" ? "text-amber-400" : "text-primary"}`}/><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="text-sm font-medium">{event.type}</p><Badge variant="outline" className="uppercase">{event.severity}</Badge></div><p className="mt-2 text-[10px] text-white/25">{new Date(event.createdAt).toLocaleString()}</p></div></div>)}</div>}
    {view === "audit" && <div className="overflow-hidden rounded-xl border border-white/[0.07]">{audit.data?.map(record => <div key={record.id} className="flex flex-col gap-2 border-b border-white/[0.06] bg-white/[0.02] p-4 last:border-0 sm:flex-row sm:items-center"><ShieldCheck className="h-4 w-4 text-white/25"/><div className="min-w-0 flex-1"><p className="text-sm font-medium">{record.action}</p><p className="text-xs text-white/30">{record.resourceType}{record.resourceId ? ` · ${record.resourceId}` : ""}</p>{record.justification && <p className="mt-1 text-xs text-amber-300/60">{record.justification}</p>}</div><Badge variant="outline">{record.result}</Badge><span className="flex items-center gap-1 text-[10px] text-white/20"><Clock3 className="h-3 w-3"/>{new Date(record.createdAt).toLocaleString()}</span></div>)}</div>}
  </div></AdminShell>;
}
