import { useEffect, useState } from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import { KeyRound, Shield, UserCheck, UserCog, UserX } from "lucide-react";
import { AdminShell } from "@/components/admin/AdminShell";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Sheet, SheetContent, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { useCustomAuth } from "@/hooks/useCustomAuth";
import { apiRequest, queryClient } from "@/lib/queryClient";

interface UserRecord { id: string; email: string | null; firstName: string | null; lastName: string | null; status: string; lastLoginAt: string | null; emailVerifiedAt: string | null; createdAt: string; roles: Array<{ key: string; name: string }> }
interface RoleRecord { id: string; key: string; name: string; description: string | null; isSystem: boolean; permissions: string[] }

export default function UserManagement() {
  const { user: currentUser } = useCustomAuth();
  const [selected, setSelected] = useState<UserRecord | null>(null);
  const [selectedRoles, setSelectedRoles] = useState<string[]>([]);
  const users = useQuery<UserRecord[]>({ queryKey: ["/api/admin/users"] });
  const roles = useQuery<RoleRecord[]>({ queryKey: ["/api/admin/roles"] });
  useEffect(() => { if (selected) setSelectedRoles(selected.roles.map(role => role.key)); }, [selected]);
  const status = useMutation({ mutationFn: ({ id, nextStatus, justification }: { id: string; nextStatus: "active" | "disabled"; justification: string }) => apiRequest("PATCH", `/api/admin/users/${id}/status`, { status: nextStatus, justification }), onSuccess: () => { queryClient.invalidateQueries({ queryKey: ["/api/admin/users"] }); queryClient.invalidateQueries({ queryKey: ["/api/admin/security/sessions"] }); } });
  const saveRoles = useMutation({ mutationFn: ({ id, justification }: { id: string; justification: string }) => apiRequest("PUT", `/api/admin/users/${id}/roles`, { roleKeys: selectedRoles, justification }), onSuccess: () => { setSelected(null); queryClient.invalidateQueries({ queryKey: ["/api/admin/users"] }); queryClient.invalidateQueries({ queryKey: ["/api/admin/security/sessions"] }); } });
  return <AdminShell title="Users and roles" description="Control administrator access, role assignments, and account state"><div className="space-y-6">
    <div className="rounded-xl border border-amber-500/20 bg-amber-500/[0.04] p-4 text-sm text-amber-100/70"><strong className="text-amber-300">Controlled provisioning:</strong> new administrators are created through the one-time bootstrap process until signed invitation and password-enrollment flows are implemented. No default passwords are generated here.</div>
    <div className="grid gap-4">{users.data?.map(user => { const name = [user.firstName, user.lastName].filter(Boolean).join(" ") || user.email || "Unknown user"; const isSelf = user.id === currentUser?.id; return <Card key={user.id} className="border-white/[0.07] bg-white/[0.025]"><CardContent className="flex flex-col gap-4 p-5 lg:flex-row lg:items-center"><div className={`flex h-11 w-11 items-center justify-center rounded-full ${user.status === "active" ? "bg-emerald-500/10 text-emerald-400" : "bg-red-500/10 text-red-400"}`}>{user.status === "active" ? <UserCheck className="h-5 w-5"/> : <UserX className="h-5 w-5"/>}</div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="font-semibold">{name}</p>{isSelf && <Badge className="bg-primary/15 text-primary">You</Badge>}<Badge variant="outline" className={user.status === "active" ? "border-emerald-500/30 text-emerald-400" : "border-red-500/30 text-red-400"}>{user.status}</Badge></div><p className="mt-1 text-xs text-white/35">{user.email}</p><div className="mt-2 flex flex-wrap gap-1.5">{user.roles.map(role => <Badge key={role.key} variant="outline" className="text-[9px]">{role.name}</Badge>)}</div><p className="mt-2 text-[10px] text-white/20">Last login: {user.lastLoginAt ? new Date(user.lastLoginAt).toLocaleString() : "Never"}</p></div><div className="flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={() => setSelected(user)}><UserCog className="mr-2 h-4 w-4"/>Roles</Button><Button size="sm" variant={user.status === "active" ? "destructive" : "default"} disabled={status.isPending || (isSelf && user.status === "active")} onClick={() => { const nextStatus = user.status === "active" ? "disabled" : "active"; const justification = window.prompt(`Justification for setting this account to ${nextStatus} (minimum 8 characters):`); if (justification && justification.trim().length >= 8) status.mutate({ id: user.id, nextStatus, justification: justification.trim() }); }}>{user.status === "active" ? "Disable" : "Activate"}</Button></div></CardContent></Card>; })}</div>
    <Sheet open={Boolean(selected)} onOpenChange={open => { if (!open) setSelected(null); }}><SheetContent className="w-full overflow-y-auto border-white/[0.07] bg-[#0b0e18] sm:max-w-lg"><SheetHeader><SheetTitle>Assign roles</SheetTitle></SheetHeader>{selected && <div className="mt-6 space-y-5"><div><p className="font-medium">{selected.email}</p><p className="mt-1 text-xs text-white/35">Changing roles increments the account security version and revokes existing sessions.</p></div><div className="space-y-2">{roles.data?.map(role => { const checked = selectedRoles.includes(role.key); return <label key={role.id} className={`block cursor-pointer rounded-xl border p-4 ${checked ? "border-primary/30 bg-primary/[0.05]" : "border-white/[0.07]"}`}><div className="flex items-start gap-3"><input className="mt-1" type="checkbox" checked={checked} onChange={event => setSelectedRoles(event.target.checked ? [...selectedRoles, role.key] : selectedRoles.filter(key => key !== role.key))}/><div className="flex-1"><div className="flex items-center gap-2"><Shield className="h-4 w-4 text-white/30"/><p className="text-sm font-medium">{role.name}</p></div><p className="mt-1 text-xs text-white/35">{role.description}</p><p className="mt-2 flex items-center gap-1 text-[10px] text-white/20"><KeyRound className="h-3 w-3"/>{role.permissions.length} permissions</p></div></div></label>; })}</div>{saveRoles.error && <p className="text-sm text-destructive">{saveRoles.error.message}</p>}<Button className="w-full" disabled={!selectedRoles.length || saveRoles.isPending} onClick={() => { const justification = window.prompt("Justification for changing roles (minimum 8 characters):"); if (justification && justification.trim().length >= 8) saveRoles.mutate({ id: selected.id, justification: justification.trim() }); }}>Apply roles and revoke sessions</Button></div>}</SheetContent></Sheet>
  </div></AdminShell>;
}
